### ISSUE TITLE
bootstrap fails with pip syntax error

### ISSUE THREAD

**Issue by wadells** [gravitational/robotest#279]
I'm seeing some robotest runs fail to initialize nodes with the following bootstrap error

```
+ curl https://bootstrap.pypa.io/get-pip.py
+ python -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1883k  100 1883k    0     0  10.3M      0 --:--:-- --:--:-- --:--:-- 10.3M
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpynAoMj/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

Likely because pip dropped support for python 2: https://pip.pypa.io/en/stable/news/#id1

https://github.com/gravitational/pithos-app/pull/139#issuecomment-767711937

**Comment by wadells** [comment]
I ported this to version/2.2 and released v2.2.1 as a hotfix.
